source 'https://rubygems.org'

#gem 'jekyll', '~> 4.2'
gem 'github-pages', '~> 215', group: :jekyll_plugins
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'jekyll-seo-tag'

group :jekyll_plugins do
  gem 'jekyll-timeago', '~> 0.13.1'
end
